# Generated by Django 4.0.2 on 2022-02-23 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_delete_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=ckeditor.fields.RichTextField(default='q'),
            preserve_default=False,
        ),
    ]
