# Generated by Django 4.0.2 on 2022-02-28 19:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='code',
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=ckeditor.fields.RichTextField(default='q'),
            preserve_default=False,
        ),
    ]
