# Generated by Django 4.0.2 on 2022-02-28 20:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_question_code_alter_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='method',
            field=ckeditor.fields.RichTextField(default='q'),
            preserve_default=False,
        ),
    ]
