# Generated by Django 4.0.2 on 2022-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='method',
            field=models.TextField(),
        ),
    ]
