# Generated by Django 4.0.2 on 2022-03-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
