# Generated by Django 4.0.2 on 2022-03-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='date_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
