# Generated by Django 4.0.2 on 2022-03-07 23:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_date_date_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='text',
            field=ckeditor.fields.RichTextField(default='q'),
            preserve_default=False,
        ),
    ]
